---
name: Build and push containerized application to GCP Container Registry
on:
  push:
  release:
    types:
      - published

jobs:
    build-and-push:
        name: Builds container and push to GCP
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: terra-kion
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v1'
          with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}
        
        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v1'
          with:
            version: '>= 434.0.0'

        - name: 'Use gcloud CLI'
          run: 'gcloud info'
