---
name: Build and push containerized application to GCP Container Registry
on:
  push:
  release:
    types:
      - published

jobs:
    build-and-push:
        name: Builds container and push to GCP
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: terra-kion
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        
        - uses: google-github-actions/setup-gcloud@master
          with:
            service_account_key: ${{ secrets.GCP_SA_KEY }}
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            export_default_credentials: true
        
        - name: Build Docker Image
          run: docker build -t $IMAGE_NAME:latest .
        
        - name: Configure Docker to use the gcloud command-line tool as a credential helper
          run: |-
            gcloud auth configure-docker --quiet
        
        - name: Push Docker Image
          env:
            GIT_TAG: v0.0.1-beta
          run: |-
            docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
            docker tag $IMAGE_NAME:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME:$GIT_TAG
            docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
            docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME:$GIT_TAG