---
name: Builds and push application then deploy to GCP
on:
  release:
    types:
      - published

jobs:
    build-and-deploy:
        name: Builds container and push to GCP
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: terra-kion
          GIT_TAG: ${{  github.ref_name }}
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v1'
          with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}
        
        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v1'
          with:
            version: '>= 434.0.0'

        - name: Deploy to GCP using Ansible
          run: ansible-playbook gcp-deploy.yml
