---
name: Build and push containerized application to GCP Container Registry
on:
  push:
  release:
    types:
      - published

jobs:
    build-and-push:
        name: Builds container and push to GCP
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: terra-kion
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v1'
          with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}
        
        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v1'
          with:
            version: '>= 434.0.0'

        - name: Build Docker Image
          run: docker build -t $IMAGE_NAME:latest .
        
        - name: Configure Docker to use the gcloud command-line tool as a credential helper
          run: gcloud auth configure-docker
        
        - name: Push Docker Image to Container Registry (GCR)
          env:
            GIT_TAG: v0.0.1-alpha
          run: |-
            docker tag $IMAGE_NAME:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME:latest
            docker tag $IMAGE_NAME:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME:$GIT_TAG
            docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME:latest
            docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME:$GIT_TAG
